services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  bucket:
    image: minio/minio
    container_name: minio
    ports:
      - 9001:9001
      - 9002:9002
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
      - MINIO_BROWSER_REDIRECT=false
    volumes:
      - ./bucket-data/data:/data
    command: minio server /data --address ":9002" --console-address ":9001"
    restart: unless-stopped
