services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  bucket:
    image: minio/minio
    ports:
      - 9001:9001
      - 9002:9002
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
      - MINIO_BROWSER_REDIRECT=false
    volumes:
      - ./bucket-data/data:/data
    command: minio server /data --address ":9002" --console-address ":9001"
    restart: unless-stopped

  umami-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./umami-data/db:/var/lib/postgresql/data
    restart: always

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql

      HASH_SALT: "${UMAMI_HASH_SALT:-random-salt-value}"
      NODE_ENV: production
    depends_on:
      - umami-db
    restart: always
